"""empty message

Revision ID: 464e25f9b379
Revises: 15badff871ce
Create Date: 2024-07-21 16:31:38.235647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464e25f9b379'
down_revision = '15badff871ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('q_answers', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    # ### end Alembic commands ###
