"""empty message

Revision ID: ac9fc8ce49e1
Revises: a8a8da8726e8
Create Date: 2024-07-21 22:11:17.697955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9fc8ce49e1'
down_revision = 'a8a8da8726e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.String(), nullable=True))
        batch_op.drop_column('answers_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###
